version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - ocramius
  - Nek-
  assignees:
  - ocramius
  - Nek-
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: phar-io/version
    versions:
    - 3.1.0
